services:
  - type: web
    name: cookbook-backend
    env: python
    region: frankfurt
    buildCommand: |
      cd Backend && pip install -r requirements.txt
      python -c "from app import db, app; app.app_context().push(); db.create_all()"
    startCommand: cd Backend && gunicorn app:app --bind 0.0.0.0:$PORT --workers=2 --threads=4
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DATABASE_URL
        fromDatabase:
          name: cookbook-db
          property: connectionString
      - key: IMGBB_API_KEY
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: ENVIRONMENT
        value: production
      - key: FLASK_APP
        value: app.py
      - key: FLASK_ENV
        value: production

databases:
  - name: cookbook-db
    plan: free
    region: frankfurt